#!/bin/bash
## bump version

echo "deprecated: checkout `npm version --help`"
exit 1;

set -e
set -o pipefail

o=$(./version)
if [ $# == 1 ]; then
  v=$1
else
  v=$(echo "$o" | awk -F '.' '{print $1 "." $2 "." $3+1}')
fi
echo "set version $o -> $v"

sed -i "s/\"version\": \".*\"/\"version\": \"$v\"/" package.json
