#!/bin/bash
function main {
  pwd=$PWD
  cd "$1"
  ls \
  | grep -v '^index.ts$' \
  | grep -v '.html$' \
  | grep -v '.scss$' \
  | grep -v '.json$' \
  | grep -v '.spec.ts' \
  | grep -v '.js$' \
  | grep -v '.js.map$' \
  | grep -v '.md$' \
  | grep -v '.asciidoc$' \
  | sed 's/\.ts//' \
  | awk '{print "export * from \"./" $1 "\";"}' \
  > index.ts
  cd "$pwd"
  return 0
}
for f in $(find src -type d -not -empty -not -path "src/assets*"); do
  main "$f"
done
cd src
cat index.ts \
  | grep -v assets \
  | grep -v theme \
  | grep -v service-worker.js \
  | grep -v test \
  > index.ts.tmp
mv index.ts.tmp index.ts
