#!/bin/bash
set -e

res=$(git status | grep "nothing to commit" | wc -l)
if [ "$res" != 1 ]; then
  echo "Error: unclean working directory, please commit changes first."
  exit 1
fi

hash pnpm 2>/dev/null && pnpm i --prefer-offline || npm i

if [ $# == 1 ]; then
  t=$1
else
  npm version --help | grep -oh "\[.*]" | grep patch  | grep minor | xargs -I {} echo -n "{}: "
  read t
fi
npm run format
npm test
rm -rf package-lock.json
npm version "$t"
./build-lib
cd dist
npm publish
git push --follow-tags
