export const allFruits = [
  'apple',
  'banana',
  'cherry',
  'date',
  'elderberry',
  'fig',
  'grape',
  'honeydew',
  'jackfruit',
  'kiwi',
  'lemon',
  'mango',
  'nectarine',
  'orange',
  'pear',
  'raspberry',
  'strawberry',
  'tangerine',
  'watermelon',
]

export const fruits = {
  apple: 'apple',
  banana: 'banana',
  cherry: 'cherry',
  date: 'date',
  elderberry: 'elderberry',
  fig: 'fig',
  grape: 'grape',
  honeydew: 'honeydew',
  jackfruit: 'jackfruit',
  kiwi: 'kiwi',
  lemon: 'lemon',
  mango: 'mango',
  nectarine: 'nectarine',
  orange: 'orange',
  pear: 'pear',
  raspberry: 'raspberry',
  strawberry: 'strawberry',
  tangerine: 'tangerine',
  watermelon: 'watermelon',
}
